version: "1"

services:
  app:
    container_name: app
    tty: true
    build:
      context: .
      dockerfile: dockerfile
      network: dcgk88c
    env_file:
      - ./.env
    expose:
      - 3001
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - WATCHPACK_POLLING=true
    networks:
      - dcgk88c
    volumes:
      - .:/app
    restart: unless-stopped

networks:
  dcgk88c:
    external: true
