[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
YARN_VERSION='4.3.1'

[phases.build]
dependsOn = ['install']
cmds = ['yarn run build']
cacheDirectories = [
'.next/cache',
'node_modules/.cache',
]

[phases.install]
dependsOn = ['setup']
cmds = [
'npm install -g corepack@0.24.1 && corepack enable',
'corepack prepare yarn@4.3.1 --activate',
'yarn set version 4.3.1',
'yarn install',
]
cacheDirectories = ['/usr/local/share/.cache/yarn/v6']
paths = ['/app/node_modules/.bin']

[phases.setup]
nixPkgs = [
'nodejs_22',
'yarn-berry',
]
nixLibs = ['gcc-unwrapped']

[start]
cmd = 'yarn run start'