const cdn = process.env.NEXT_PUBLIC_CDN || "";

export const icons = {
  albedo: `${cdn}/assets/icon/albedo_icon.webp`,
  alhaitham: `${cdn}/assets/icon/alhaitham_icon.webp`,
  arataki_itto: `${cdn}/assets/icon/arataki_itto_icon.webp`,
  baizhu: `${cdn}/assets/icon/baizhu_icon.webp`,
  chiori: `${cdn}/assets/icon/chiori_icon.webp`,
  cyno: `${cdn}/assets/icon/cyno_icon.webp`,
  dehya: `${cdn}/assets/icon/dehya_icon.webp`,
  diluc: `${cdn}/assets/icon/diluc_icon.webp`,
  eula: `${cdn}/assets/icon/eula_icon.webp`,
  furina: `${cdn}/assets/icon/furina_icon.webp`,
  ganyu: `${cdn}/assets/icon/ganyu_icon.webp`,
  hu_tao: `${cdn}/assets/icon/hu_tao_icon.webp`,
  jean: `${cdn}/assets/icon/jean_icon.webp`,
  kaedehara_kazuha: `${cdn}/assets/icon/kaedehara_kazuha_icon.webp`,
  kamisato_ayaka: `${cdn}/assets/icon/kamisato_ayaka_icon.webp`,
  kamisato_ayato: `${cdn}/assets/icon/kamisato_ayato_icon.webp`,
  keqing: `${cdn}/assets/icon/keqing_icon.webp`,
  klee: `${cdn}/assets/icon/klee_icon.webp`,
  lyney: `${cdn}/assets/icon/lyney_icon.webp`,
  mona: `${cdn}/assets/icon/mona_icon.webp`,
  nahida: `${cdn}/assets/icon/nahida_icon.webp`,
  navia: `${cdn}/assets/icon/navia_icon.webp`,
  neuvillette: `${cdn}/assets/icon/neuvillette_icon.webp`,
  nilou: `${cdn}/assets/icon/nilou_icon.webp`,
  qiqi: `${cdn}/assets/icon/qiqi_icon.webp`,
  raiden_shogun: `${cdn}/assets/icon/raiden_shogun_icon.webp`,
  sangonomiya_kokomi: `${cdn}/assets/icon/sangonomiya_kokomi_icon.webp`,
  shenhe: `${cdn}/assets/icon/shenhe_icon.webp`,
  tartaglia: `${cdn}/assets/icon/tartaglia_icon.webp`,
  tighnari: `${cdn}/assets/icon/tighnari_icon.webp`,
  venti: `${cdn}/assets/icon/venti_icon.webp`,
  wanderer: `${cdn}/assets/icon/wanderer_icon.webp`,
  wriothesley: `${cdn}/assets/icon/wriothesley_icon.webp`,
  xianyun: `${cdn}/assets/icon/xianyun_icon.webp`,
  xiao: `${cdn}/assets/icon/xiao_icon.webp`,
  yae_miko: `${cdn}/assets/icon/yae_miko_icon.webp`,
  yelan: `${cdn}/assets/icon/yelan_icon.webp`,
  yoimiya: `${cdn}/assets/icon/yoimiya_icon.webp`,
  zhongli: `${cdn}/assets/icon/zhongli_icon.webp`,
  arlecchino: `${cdn}/assets/icon/arlecchino_icon.webp`,
  clorinde: `${cdn}/assets/icon/clorinde_icon.webp`,
  emilie: `${cdn}/assets/icon/emilie_icon.webp`,
  sigewinne: `${cdn}/assets/icon/sigewinne_icon.webp`,
};

export const characters = {
  albedo: `${cdn}/assets/portrait/albedo_profile.webp`,
  alhaitham: `${cdn}/assets/portrait/alhaitham_profile.webp`,
  arataki_itto: `${cdn}/assets/portrait/arataki_itto_profile.webp`,
  baizhu: `${cdn}/assets/portrait/baizhu_profile.webp`,
  chiori: `${cdn}/assets/portrait/chiori_profile.webp`,
  cyno: `${cdn}/assets/portrait/cyno_profile.webp`,
  dehya: `${cdn}/assets/portrait/dehya_profile.webp`,
  diluc: `${cdn}/assets/portrait/diluc_profile.webp`,
  eula: `${cdn}/assets/portrait/eula_profile.webp`,
  furina: `${cdn}/assets/portrait/furina_profile.webp`,
  ganyu: `${cdn}/assets/portrait/ganyu_profile.webp`,
  hu_tao: `${cdn}/assets/portrait/hu_tao_profile.webp`,
  jean: `${cdn}/assets/portrait/jean_profile.webp`,
  kaedehara_kazuha: `${cdn}/assets/portrait/kaedehara_kazuha_profile.webp`,
  kamisato_ayaka: `${cdn}/assets/portrait/kamisato_ayaka_profile.webp`,
  kamisato_ayato: `${cdn}/assets/portrait/kamisato_ayato_profile.webp`,
  keqing: `${cdn}/assets/portrait/keqing_profile.webp`,
  klee: `${cdn}/assets/portrait/klee_profile.webp`,
  lyney: `${cdn}/assets/portrait/lyney_profile.webp`,
  mona: `${cdn}/assets/portrait/mona_profile.webp`,
  nahida: `${cdn}/assets/portrait/nahida_profile.webp`,
  navia: `${cdn}/assets/portrait/navia_profile.webp`,
  neuvillette: `${cdn}/assets/portrait/neuvillette_profile.webp`,
  nilou: `${cdn}/assets/portrait/nilou_profile.webp`,
  qiqi: `${cdn}/assets/portrait/qiqi_profile.webp`,
  raiden_shogun: `${cdn}/assets/portrait/raiden_shogun_profile.webp`,
  sangonomiya_kokomi: `${cdn}/assets/portrait/sangonomiya_kokomi_profile.webp`,
  shenhe: `${cdn}/assets/portrait/shenhe_profile.webp`,
  tartaglia: `${cdn}/assets/portrait/tartaglia_profile.webp`,
  tighnari: `${cdn}/assets/portrait/tighnari_profile.webp`,
  venti: `${cdn}/assets/portrait/venti_profile.webp`,
  wanderer: `${cdn}/assets/portrait/wanderer_profile.webp`,
  wriothesley: `${cdn}/assets/portrait/wriothesley_profile.webp`,
  xianyun: `${cdn}/assets/portrait/xianyun_profile.webp`,
  xiao: `${cdn}/assets/portrait/xiao_profile.webp`,
  yae_miko: `${cdn}/assets/portrait/yae_miko_profile.webp`,
  yelan: `${cdn}/assets/portrait/yelan_profile.webp`,
  yoimiya: `${cdn}/assets/portrait/yoimiya_profile.webp`,
  zhongli: `${cdn}/assets/portrait/zhongli_profile.webp`,
  arlecchino: `${cdn}/assets/portrait/arlecchino_profile.webp`,
  clorinde: `${cdn}/assets/portrait/clorinde_profile.webp`,
  emilie: `${cdn}/assets/portrait/emilie_profile.webp`,
  sigewinne: `${cdn}/assets/portrait/sigewinne_profile.webp`,
};

export const backgrounds = {
  fontaine: `${cdn}/assets/backgrounds/fontaine.webp`,
  inazuma: `${cdn}/assets/backgrounds/inazuma.webp`,
  liyue: `${cdn}/assets/backgrounds/liyue.webp`,
  sumeru: `${cdn}/assets/backgrounds/sumeru.webp`,
  mondstadt: `${cdn}/assets/backgrounds/mondstadt.webp`,
};

export const elements = {
  anemo: `${cdn}/assets/elements/element_anemo.svg`,
  geo: `${cdn}/assets/elements/element_geo.svg`,
  electro: `${cdn}/assets/elements/element_electro.svg`,
  hydro: `${cdn}/assets/elements/element_hydro.svg`,
  pyro: `${cdn}/assets/elements/element_pyro.svg`,
  cryo: `${cdn}/assets/elements/element_cryo.svg`,
  dendro: `${cdn}/assets/elements/element_dendro.svg`,
};
