export const icons = {
  albedo: "/assets/icon/albedo_icon.webp",
  alhaitham: "/assets/icon/alhaitham_icon.webp",
  arataki_itto: "/assets/icon/arataki_itto_icon.webp",
  baizhu: "/assets/icon/baizhu_icon.webp",
  chiori: "/assets/icon/chiori_icon.webp",
  cyno: "/assets/icon/cyno_icon.webp",
  dehya: "/assets/icon/dehya_icon.webp",
  diluc: "/assets/icon/diluc_icon.webp",
  eula: "/assets/icon/eula_icon.webp",
  furina: "/assets/icon/furina_icon.webp",
  ganyu: "/assets/icon/ganyu_icon.webp",
  hu_tao: "/assets/icon/hu_tao_icon.webp",
  jean: "/assets/icon/jean_icon.webp",
  kaedehara_kazuha: "/assets/icon/kaedehara_kazuha_icon.webp",
  kamisato_ayaka: "/assets/icon/kamisato_ayaka_icon.webp",
  kamisato_ayato: "/assets/icon/kamisato_ayato_icon.webp",
  keqing: "/assets/icon/keqing_icon.webp",
  klee: "/assets/icon/klee_icon.webp",
  lyney: "/assets/icon/lyney_icon.webp",
  mona: "/assets/icon/mona_icon.webp",
  nahida: "/assets/icon/nahida_icon.webp",
  navia: "/assets/icon/navia_icon.webp",
  neuvillette: "/assets/icon/neuvillette_icon.webp",
  nilou: "/assets/icon/nilou_icon.webp",
  qiqi: "/assets/icon/qiqi_icon.webp",
  raiden_shogun: "/assets/icon/raiden_shogun_icon.webp",
  sangonomiya_kokomi: "/assets/icon/sangonomiya_kokomi_icon.webp",
  shenhe: "/assets/icon/shenhe_icon.webp",
  tartaglia: "/assets/icon/tartaglia_icon.webp",
  tighnari: "/assets/icon/tighnari_icon.webp",
  venti: "/assets/icon/venti_icon.webp",
  wanderer: "/assets/icon/wanderer_icon.webp",
  wriothesley: "/assets/icon/wriothesley_icon.webp",
  xianyun: "/assets/icon/xianyun_icon.webp",
  xiao: "/assets/icon/xiao_icon.webp",
  yae_miko: "/assets/icon/yae_miko_icon.webp",
  yelan: "/assets/icon/yelan_icon.webp",
  yoimiya: "/assets/icon/yoimiya_icon.webp",
  zhongli: "/assets/icon/zhongli_icon.webp",
  arlecchino: "/assets/icon/arlecchino_icon.webp",
  clorinde: "/assets/icon/clorinde_icon.webp",
  emilie: "/assets/icon/emilie_icon.webp",
  sigewinne: "/assets/icon/sigewinne_icon.webp",
};

export const characters = {
  albedo: "/assets/portrait/albedo_profile.webp",
  alhaitham: "/assets/portrait/alhaitham_profile.webp",
  arataki_itto: "/assets/portrait/arataki_itto_profile.webp",
  baizhu: "/assets/portrait/baizhu_profile.webp",
  chiori: "/assets/portrait/chiori_profile.webp",
  cyno: "/assets/portrait/cyno_profile.webp",
  dehya: "/assets/portrait/dehya_profile.webp",
  diluc: "/assets/portrait/diluc_profile.webp",
  eula: "/assets/portrait/eula_profile.webp",
  furina: "/assets/portrait/furina_profile.webp",
  ganyu: "/assets/portrait/ganyu_profile.webp",
  hu_tao: "/assets/portrait/hu_tao_profile.webp",
  jean: "/assets/portrait/jean_profile.webp",
  kaedehara_kazuha: "/assets/portrait/kaedehara_kazuha_profile.webp",
  kamisato_ayaka: "/assets/portrait/kamisato_ayaka_profile.webp",
  kamisato_ayato: "/assets/portrait/kamisato_ayato_profile.webp",
  keqing: "/assets/portrait/keqing_profile.webp",
  klee: "/assets/portrait/klee_profile.webp",
  lyney: "/assets/portrait/lyney_profile.webp",
  mona: "/assets/portrait/mona_profile.webp",
  nahida: "/assets/portrait/nahida_profile.webp",
  navia: "/assets/portrait/navia_profile.webp",
  neuvillette: "/assets/portrait/neuvillette_profile.webp",
  nilou: "/assets/portrait/nilou_profile.webp",
  qiqi: "/assets/portrait/qiqi_profile.webp",
  raiden_shogun: "/assets/portrait/raiden_shogun_profile.webp",
  sangonomiya_kokomi: "/assets/portrait/sangonomiya_kokomi_profile.webp",
  shenhe: "/assets/portrait/shenhe_profile.webp",
  tartaglia: "/assets/portrait/tartaglia_profile.webp",
  tighnari: "/assets/portrait/tighnari_profile.webp",
  venti: "/assets/portrait/venti_profile.webp",
  wanderer: "/assets/portrait/wanderer_profile.webp",
  wriothesley: "/assets/portrait/wriothesley_profile.webp",
  xianyun: "/assets/portrait/xianyun_profile.webp",
  xiao: "/assets/portrait/xiao_profile.webp",
  yae_miko: "/assets/portrait/yae_miko_profile.webp",
  yelan: "/assets/portrait/yelan_profile.webp",
  yoimiya: "/assets/portrait/yoimiya_profile.webp",
  zhongli: "/assets/portrait/zhongli_profile.webp",
  arlecchino: "/assets/portrait/arlecchino_profile.webp",
  clorinde: "/assets/portrait/clorinde_profile.webp",
  emilie: "/assets/portrait/emilie_profile.webp",
  sigewinne: "/assets/portrait/sigewinne_profile.webp",
};

export const backgrounds = {
  fontaine: "/assets/backgrounds/fontaine.webp",
  inazuma: "/assets/backgrounds/inazuma.webp",
  liyue: "/assets/backgrounds/liyue.webp",
  sumeru: "/assets/backgrounds/sumeru.webp",
  mondstadt: "/assets/backgrounds/mondstadt.webp",
};

export const elements = {
  anemo: "/assets/elements/element_anemo.svg",
  geo: "/assets/elements/element_geo.svg",
  electro: "/assets/elements/element_electro.svg",
  hydro: "/assets/elements/element_hydro.svg",
  pyro: "/assets/elements/element_pyro.svg",
  cryo: "/assets/elements/element_cryo.svg",
  dendro: "/assets/elements/element_dendro.svg",
};
